# -*- coding: utf-8 -*-
"""Excercício 10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 10
"""

perDistribuidor = 0.28
perImpostos = 0.45

custoFabrica = float (input("Qual o custo de fábrica?: R$"))
custoDistribuidor = perDistribuidor * custoFabrica
custoImpostos = perImpostos * custoFabrica

print ('O valor final é: R$', custoFabrica+custoDistribuidor+custoImpostos)