# -*- coding: utf-8 -*-
"""Excercício 33

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 33
"""

valor1 = int(input('Valor 1:'))
valor2 = int(input('Valor 2:'))

if (valor1 == valor2):
  print('Números iguais')
elif (valor1 > valor2):
  print ('Primeiro é maior')
else:
  print ('Segundo é maior')