# -*- coding: utf-8 -*-
"""Excercício 43

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 43
"""

a = int(input('Digite um valor:'))
b = int(input('Digite um valor:'))
c = int(input('Digite um valor:'))

if (a<b+c) and (b<a+c) and (c<a+b):
  if (a==b) and (b==c):
    print ('Triângulo Equilátero')
  else:
    if (a==b) or (b==c) or (a==c):
       print ('Triângulo Isósceles')
    else:
       print ('Triângulo Escaleno')
else:
  print ('Não é possível formar um triângulo')

# a = 1, b = 2, c = 3 == Não é possível formar um triângulo
# a = 3, b = 4, c = 5 == Triângulo Escaleno
# a = 2, b = 2, c = 4 == Não é possível formar um triângulo
# a = 4, b = 4, c = 4 == Triângulo Equilátero
# a = 5, b = 3, c = 3 == Triângulo Isósceles