# -*- coding: utf-8 -*-
"""Excercício 14

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 14
"""

valor = int(input('Informe um valor:'))
if (valor > 10):
  print ('É MAIOR QUE 10!')
else :
  print ('NÃO É MAIOR QUE 10!')