# -*- coding: utf-8 -*-
"""Excercício 31

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 31
"""

A = float(input('Medida 1:'))
B = float(input('Medida 2:'))
C = float(input('Medida 3:'))

if ((A + B) > C) and ((A + C) > B) and ((B + C) > A):
  print ('Forma um triângulo')
else:
  print ('Não forma um triângulo')