# -*- coding: utf-8 -*-
"""Excercício 37

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 37
"""

print ('Quantidade em Kg')
quantMorango = float(input('Quantidade de morangos:'))
quantMaca = float(input('Quantidade de maçãs:'))

if (quantMorango <= 5):
  valorMorangos = 2.50 * quantMorango
else:
  valorMorangos = 2.20 * quantMorango

if (quantMaca <= 5):
  valorMaca = 1.80 * quantMaca
else:
  valorMaca = 1.50 * quantMaca
  
valorTotal = valorMorangos + valorMaca

print ('O valor total é: R$', valorTotal)

if ((quantMorango) or (quantMaca)) > 8 or ((valorMaca) or (valorMorango)) > 25:
  desconto = 0.10
  valorDesconto = (valorTotal * desconto)
  valorFinal = valorTotal - valorDesconto
  print ('Você ganhou 10% de desconto!')
  print ('O valor final é: R$', valorFinal)