# -*- coding: utf-8 -*-
"""Excercício 36

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 36
"""

idadeH1 = int(input('Idade Homem 1:'))
idadeH2 = int(input('Idade Homem 2:'))
idadeM1 = int(input('Idade Mulher 1:'))
idadeM2 = int(input('Idade Mulher 2:'))

if (idadeH1 > idadeH2):
  maisVelho = idadeH1
  maisNovo = idadeH2
else:
  maisVelho = idadeH2
  maisNovo = idadeH1

if (idadeM1 > idadeM2):
  maisNova = idadeM2
  maisVelha = idadeM1
else:
  maisNova = idadeM1
  maisVelha = idadeM2

print ('A soma das idades do homem mais velho + mulher mais nova é:', maisVelho + maisNova)
print ('O produto das idades do homem mais novo / mulher mais velha é:', maisNovo/maisVelha)