# -*- coding: utf-8 -*-
"""Excercício 41

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 41
"""

N1 = float(input('Nota 1:'))
N2 = float(input('Nota 2:'))
N3 = float(input('Nota 3:'))
Media_dos_Exercicios = (N1*N2*N3)/3
Media_de_Aproveitamento = (N1 + N2 * 2 + N3 * 3 + Media_dos_Exercicios)/7

if (Media_de_Aproveitamento >= 9.0):
  print ('Conceito A')
elif (Media_de_Aproveitamento >= 7.5) and (Media_de_Aproveitamento < 9.0):
  print ('Conceito B')
elif (Media_de_Aproveitamento >= 6.0) and (Media_de_Aproveitamento < 7.5):
  print ('Conceito C')
else:
  print ('Conceito D')