# -*- coding: utf-8 -*-
"""Excercício 13 Horizontalização

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 13
"""

n1 = float(input('Informe a Nota 1:'))
n2 = float(input('Informe a Nota 2:'))
n3 = float(input('Informe a Nota 3:'))

mediafinal = (n1*2 + n2*3 + n3*5)/10

print ('A média final é:', "%.1f" %mediafinal)