# -*- coding: utf-8 -*-
"""Excercício 2 letra F

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

2) Exercício 2 letra F
"""

X = 1
Y = 2
Z = Y - X

print (Z) #1
X = 5
Y = X + Z

print (X, Y, Z)