# -*- coding: utf-8 -*-
"""Excercício 8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 8
"""

quantEleitores = int (input('Quantidade de eleitores: '))
brancos = int (input('Quantidade de votos brancos: '))
nulos = int (input('Quantidade de votos nulos: '))
validos = int (input('Quantidade de votos válidos: '))

porcentagemBrancos = float (100*brancos/quantEleitores)
porcentagemNulos = float (100*nulos/quantEleitores)
porcentagemValidos = float (100*validos/quantEleitores)

print ('Porcentagem de votos brancos: ', porcentagemBrancos, '%')
print ('Porcentagem de votos nulos: ', porcentagemNulos, '%')
print ('Porcentagem de votos válidos: ', porcentagemValidos, '%')