# -*- coding: utf-8 -*-
"""Excercício 18

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 18
"""

anoAtual = int(input('Qual o ano atual?'))
anoNascimento = int(input('Qual seu ano de nascimento?'))
idade = anoAtual - anoNascimento
if (idade >= 16):
  print ('Você pode votar esse ano!')
else:
  print ('Você não pode votar esse ano!')