# -*- coding: utf-8 -*-
"""Excercício 2 letra D

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

2) Exercício 2 letra D

```
# Isto está formatado como código
```
"""

A = 10
B = A + 1
A = B + 1
B = A + 1

print (A)

A = B + 1

print (A,B)