# -*- coding: utf-8 -*-
"""Excercício 11

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 11
"""

carrosVendidos = int (input('Quantidade de carros vendidos: '))
valorVendas = float (input('Valor total das vendas: R$ '))
salarioFixo = float (input('Valor do salário fixo: R$ '))
valorPCarroVendido = float (input('Valor recebido por cada carro vendido: R$'))
comissaoVendas = 0.05

comissaoCarroVendido = valorPCarroVendido * carrosVendidos
comissaoTotalVendas = valorVendas * comissaoVendas

print ('O salário final é de: R$', salarioFixo+comissaoCarroVendido+comissaoTotalVendas)