# -*- coding: utf-8 -*-
"""Excercício 16

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 16
"""

quantMaca = int(input('Quantas maçãs foram compradas?'))
if (quantMaca < 12):
  total = quantMaca * 1.30
  print ('O valor total é: R$', total)
else:
  total = quantMaca * 1.00
  print ('O valor total é: R$', total)