# -*- coding: utf-8 -*-
"""Excercício 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 5
"""

valor = int (input('Digite um valor: '))
print ('Seu antecessor é:', valor - 1)

