# -*- coding: utf-8 -*-
"""Excercício 15

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 15
"""

valor = int(input('Informe um valor:'))
if (valor >= 0):
  print ('É um valor positivo!')
else:
  print ('É um valor negativo!')