# -*- coding: utf-8 -*-
"""Excercício 49

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 49
"""

class gradeIsntANumber(BaseException):
  pass 
class gradeOutOfInterval(BaseException):
  pass
def readGrade(prompt):
  try:
    result = float(input(prompt))
    if (result>10 or result<0):
      raise gradeOutOfInterval()
    return result
  except ValueError:
    raise gradeIsntANumber()
def calculateMeanUseCase():
  try:
    N1 = readGrade('Nota 1:')
    N2 = readGrade('Nota 2:')

    media = (N1 + N2)/2

    print('A média é:', media)
  
  except gradeIsntANumber:
    print('As notas precisam ser números.')
  except gradeOutOfInterval:
    print ('As notas precisam estar entre 0 e 10')
def canContinueCalculate():
  print('Novo Cálculo?')
  response = str(input('S/N:'))
  x = response.upper()
  if (x == 'S'):
    return True
  else:
    return False
mustRun = True
while (mustRun):
  calculateMeanUseCase()
  mustRun = canContinueCalculate()