# -*- coding: utf-8 -*-
"""Excercício 35

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 35
"""

precoGasolina = 3.30
precoAlcool = 2.90
litros = float(input('Número de litros vendidos:'))
print ('Tipo de combustível = A-álcool / G-gasolina')
combustivel = str(input('O tipo de combustível foi A ou G'))
c = combustivel.upper()
if (c == 'A'):
  if (litros <= 20):
    valorFinal = (precoAlcool * litros) - ((0.03 * precoAlcool) * litros)
  else:
    valorFinal = (precoAlcool * litros) - ((0.05 * precoAlcool) * litros)
  print ('Valor a ser pago: R$', valorFinal)
else:
  if (litros <= 20):
    valorFinal = (precoGasolina * litros) - ((0.04 * precoGasolina) * litros)
  else:
    valorFinal = (precoGasolina * litros) - ((0.06 * precoGasolina) * litros)
  print ('Valor a ser pago: R$', valorFinal)