# -*- coding: utf-8 -*-
"""Excercício 25

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 25
"""

conta = int(input('Número da conta do cliente:'))
saldo = float(input('Saldo do cliente:'))
debito = float(input('Débito do cliente:'))
credito = float(input('Crédito do cliente:'))

saldoAtual = saldo - debito + credito
print ('O saldo atual é de: R$', saldoAtual)

if (saldoAtual >= 0):
  print ('Saldo Positivo')
else:
  print ('Saldo Negativo')