# -*- coding: utf-8 -*-
"""Excercício 20

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 20
"""

print ( 'Digite valores inteiros e diferentes')
A = int(input('Digite um valor:'))
B = int(input('Digite outro valor:'))

if (A > B):
  print (B,'-',A)
else:
  print (A,'-',B)