# -*- coding: utf-8 -*-
"""Excercício 17

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 17
"""

nota1 = float(input('Informe a nota da primeira avaliação:'))
nota2 = float(input('Informe a nota da segunda avaliação:'))
mediaSimples = (nota1 + nota2)/2
if (mediaSimples >= 6):
  print ('O aluno foi Aprovado!')
  print ('A média foi:', mediaSimples)
else:
  print ('O aluno não foi Aprovado!')
  print ('A média foi:', mediaSimples)