# -*- coding: utf-8 -*-
"""Excercício 2 letra A.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

2) Exercício 2 letra A
"""

A = 10
B = 20

print (B)

B = 5
print (A,B)