# -*- coding: utf-8 -*-
"""Excercício 1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

1) Exercício 1
"""

A = 10
B = 20
C = A
A = B
B = C

print (A, B)