# -*- coding: utf-8 -*-
"""Excercício 44

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 44
"""

a = int(input('Digite um valor para A:'))
b = int(input('Digite um valor para B:'))

if (b == 0):
  b = int(input('Digite um valor para B:'))
if (b == 0):
  b = int(input('Digite um valor para B:'))
if (b == 0):
  b = int(input('Digite um valor para B:'))
else:
  print('O resultado da divisão entre os valores lidos é:', a/b)