# -*- coding: utf-8 -*-
"""Excercício 12 Horizontalização

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 12
"""

F = float(input('Temperatura em Fahrenheit:'))
C = ((F-32)*5)/9
print ('A temperatura em graus CELSIUS é:',"%.3f"% C,'°')