# -*- coding: utf-8 -*-
"""Excercício 42

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 42
"""

print ('Digite seu código:')
codigo = str(input(''))
ano = int(input('Qual seu ano de nascimento?'))
anoEmpresa = int (input('Qual seu ano de ingresso na empresa?'))
anoAtual = 2022

idade = anoAtual - ano
tempoDeTrabalho = anoAtual - anoEmpresa

print ('Idade:',idade)
print ('Tempo de trabalho na empresa:',tempoDeTrabalho)

if idade >= 65 or tempoDeTrabalho >= 30 or (idade >= 60 and tempoDeTrabalho >= 25):
  print ('Requerer aposentadoria')
else:
  print ('Não requerer')