# -*- coding: utf-8 -*-
"""Excercício 19

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 19
"""

valor1 = int(input('Digite um valor:'))
valor2 = int(input('Digite outro valor:'))
if (valor1 > valor2):
  print(valor1)
elif (valor1 == valor2):
  print ('Valores iguais não serão lidos.')
else:
  print (valor2)