# -*- coding: utf-8 -*-
"""Excercício 22

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 22
"""

horasSemanais = 40
semanas = 4
horasPorMes = int(input('Quantas horas foram trabalhadas este mês?'))
salarioPHora = float(input('Qual o salário por hora?'))
acrescimoHoraExtra = 0.50 * salarioPHora
totalHorasSemanais = horasPorMes/semanas
salarioPadrao = (horasSemanais * semanas) * salarioPHora

if (totalHorasSemanais > horasSemanais):
  horasExtras = (totalHorasSemanais - horasSemanais) * semanas
  salarioFinal = (horasExtras * acrescimoHoraExtra) + salarioPadrao
  print ('Seu salário final é de: R$', salarioFinal)
else:
  print ('Seu salário final é de: R$', salarioPadrao)