# -*- coding: utf-8 -*-
"""Excercício 28

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 28
"""

print ('Informe valores diferentes!')
valor1 = int(input('Informe um valor:'))
valor2 = int(input('Informe um valor:'))
valor3 = int(input('Informe um valor:'))

if (valor1 > valor2 > valor3):
  print(valor1)
elif (valor2 > valor1 > valor3):
  print(valor2)
else:
  print(valor3)