# -*- coding: utf-8 -*-
"""Excercício 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 4
"""

A = 6*(3+2)
print (A)

A = 6*3 + 6*2
print (A)

B = 2+(6*(3+2))
print (B)

B = 2+(6*3 + 6*2)
print (B)

C = 2+(3*6)/(2+4)
print (C)

C = 2+3*6/(2+4)
print (C)

D = 2*(8/(3+1))
print (D)

D = 2*8/(3+1)
print (D)

E = 3+(16-2)/(2*(9-2))
print (E)

E = 3+(16-2)/(2*9 - 2*2)
print (E)

F = (6/3)+(8/2)
print (F)

F = 6/3+8/2
print (F)

G = ((3+(8/2))*4)+(3*2)
print (G)

G = (3+8/2)*4+3*2
print (G)

H = (6*(3*3)+6)-10
print (H)

H = 6*3*3+6-10
print (H)

I = (((10*8)+3)*9)
print (I)

I = (10*8+3)*9
print (I)

J = ((-12)*(-4))+(3*(-4))
print (J)

J = -12*-4+3*-4
print (J)

