# -*- coding: utf-8 -*-
"""Excercício 32

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 32
"""

time1 = str(input('Nome do time 1:'))
golsTime1 = int(input('Quantidade de gols do time 1:'))
time2 = str(input('Nome do time 2:'))
golsTime2 = int(input('Quantidade de gols do time 2:'))

if (golsTime1 == golsTime2):
  print('EMPATE')
elif (golsTime1 > golsTime2):
  print('Quem ganhou a partida foi o time:', time1)
else:
  print('Quem ganhou a partida foi o time:', time2)