# -*- coding: utf-8 -*-
"""Excercício 39

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 39
"""

def letterA(A,B,C):
  result = (A and B) or (A ^ B)
  print(f'(A and B) or (A xor B) = {result}')

def letterB(A,B,C):
  result = (A or B) and (A and C)
  print(f'(A or B) and (A and C) = {result}')

def letterC(A,B,C):
  result = (A or C) and (B ^ A) and not B
  print(f'(A or C) and (B ^ A) and not B = {result}')

A = True
B = True
C = False

letterA(A,B,C)
letterB(A,B,C)
letterC(A,B,C)