# -*- coding: utf-8 -*-
"""Excercício 2 letra E

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

2) Exercício 2 letra E

```
# Isto está formatado como código
```
"""

A = 10
B = 5
C = A + B
B = 20
A = 10

print (A, B, C)