# -*- coding: utf-8 -*-
"""Excercício 2 letra B

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

2) Exercício 2 letra B
"""

A = 30
B = 20
C = A + B

print (C)

B = 10

print (B, C)

C = A + B

print (A, B, C)