# -*- coding: utf-8 -*-
"""Excercício 38

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 38
"""

print('Digite o usuário:')
codigo = str(input('Usuário:'))
print('Digite a senha:')
senha = str(input('Senha:'))

if (codigo != '1234') and (senha != '9999'):
    print('Usuário inválido')
    print('Senha incorreta')
elif (codigo == '1234') and (senha != '9999'):
    print('Senha incorreta')
elif (codigo != '1234') and (senha == '9999'):
    print('Usuário inválido')
else:
    print('Acesso permitido')
