# -*- coding: utf-8 -*-
"""Excercício 38

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 38
"""

print ('Digite um código:')
codigo = int(input('código:'))

if (codigo != 1234):
  print ('Usuário inválido!')
else:
  senha = int(input('Digite a senha:'))
  if (senha != 9999):
    print('senha incorreta')
  else:
    print('Acesso permitido')