# -*- coding: utf-8 -*-
"""Excercício 40

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 40
"""

nome = str(input('Nome do produto:'))
quantidade = int(input('Quantidade adquirida:'))
precoUnitario = float(input('Preço unitário:'))
total = quantidade * precoUnitario
print ('O total é de: R$', total)

if (quantidade <= 5):
  desconto = 0.02 * total
elif (quantidade > 5) and (quantidade <= 10):
  desconto = 0.03 * total
else:
  desconto = 0.05 * total

totalAPagar = total - desconto

print ('Você ganhou um desconto de: R$:',desconto)
print ('Total a pagar: R$', totalAPagar)