# -*- coding: utf-8 -*-
"""Excercício 2 letra C

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

2) Exercício 2 letra C

```
# Isto está formatado como código
```
"""

A = 10
B = 20
C = A
B = C
A = B

print (A, B, C)