# -*- coding: utf-8 -*-
"""Excercício 24

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 24
"""

padraoVendas = 1500
salarioFixo = float(input('Qual o salário fixo?'))
valorVendas = float(input('Valor das vendas efetuadas:'))
if (valorVendas < padraoVendas):
  salarioTotal = (valorVendas * 0.03) + salarioFixo
  print ('O salário total é: R$', salarioTotal)
else:
  valorAMais = valorVendas - padraoVendas
  salarioTotal = ((padraoVendas * 0.03) + (valorAMais * 0.05)) + salarioFixo
  print ('O salário total é: R$', salarioTotal)