# -*- coding: utf-8 -*-
"""Excercício 34

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 34
"""

x = int(input('valor para x:'))
y = int(input('valor para y:'))
z = (x*y) + 5
if (z <= 0):
  resposta = 'A'
elif (z <= 100):
  resposta = 'B'
else:
  resposta = 'C'
print (z, resposta)

# 11 B
# 455 C
# -2 A
# -5 A
# 155 C