# -*- coding: utf-8 -*-
"""Excercício 9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 9
"""

salario = float (input('Informe seu salário: R$'))
reajuste = float (input('Percentual de reajuste: '))
acao = (input('Para Mais ou para Menos?'))
x = acao.upper()
precoReajuste = (reajuste * salario)/100

if (x == "MAIS"):
  precoFinal = precoReajuste + salario

else :
  precoFinal = salario - precoReajuste

print ('O novo valor é de: R$', precoFinal)