# -*- coding: utf-8 -*-
"""Excercício 47

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 47
"""

a = int(input('Digite um valor para A:'))
b = int(input('Digite um valor para B:'))

while (b == 0):
  print ('Valor Inválido')
  b = int(input('Digite um valor para B:'))
print('O resultado da divisão entre os valores lidos é:', a/b)