# -*- coding: utf-8 -*-
"""Excercício 27

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 27
"""

valor = int(input('Valor: '))
if (valor == 0):
  print ('O valor é 0')
elif (valor > 0):
    print ('O valor é positivo!')
else:
    print ('O valor é negativo!')