# -*- coding: utf-8 -*-
"""Excercício 6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 6
"""

base = float (input('Base do retângulo: '))
altura = float (input('Altura do retângulo: '))
uMedida = input('Unidade de medida: ')
area = base * altura

print ('A área do retângulo é: ', area, uMedida,'²')

