# -*- coding: utf-8 -*-
"""Excercício 21

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 21
"""

duracaoMaxima = 24
print ('Em formato de 24 Horas, informe:')
horaInicio = int(input('Horário de início da partida:'))
horaFim = int(input('Horário do fim da partida:'))
if (horaInicio == horaFim):
  print('Foi excedido o tempo máximo de jogo')
elif (horaInicio <= horaFim):
  duracao = horaFim-horaInicio
  print('A duração da partida foi de:', duracao,'horas')
else:
  duracao = (duracaoMaxima-horaInicio)+horaFim
  print('A duração da partida foi de:', duracao,'horas')