# -*- coding: utf-8 -*-
"""Excercício 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1qfpENv0omMLvWe03GtXJIu1va_rf3O

Exercício 3
"""

A = (4/2) + (2/4)

print (A)

A = 4/2+2/4

print (A)

#Os pares da letra A produzem os mesmos resultados

B = 4/(2+2)/4

print (B)

B = 4/2+2/4

print (B)

#Os pares da letra B não produzem os mesmos resultados

C = (4+2)*2-4

print (C)

C = 4+2*2-4

print (C)

#Os pares da letra C não produzem os mesmos resultados